{{- if .Values.kafkaUI.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafka-ui-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.kafkaUI.hostname }}"
    nginx.ingress.kubernetes.io/proxy-body-size: "15m"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: "{{ .Values.kafkaUI.hostname }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "kafka.fullname" . }}-kafka-ui
            port: 
              number: 8080
{{- end }}
{{- if .Values.kafka.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafka-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.kafka.ingress.hostname }}"
    nginx.ingress.kubernetes.io/proxy-body-size: "15m"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: "{{ .Values.kafka.ingress.hostname }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kafka-svc
            port: 
              number: 9092
{{- end }}