{{- if .Values.debezium.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.debezium.serviceAccount }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.debezium.roleArn }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developers-edit-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: Group
    name: developers
    namespace: {{ .Release.Namespace }}
{{- end }}