{{- if .Values.debezium.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "rmc-digital/{{ .Values.env }}/product-configurator/postgres"
        objectType: "secretsmanager"
        objectVersionLabel: "AWSCURRENT"
{{- end }}